export const REQUEST_PERMISSION = "REQUEST_PERMISSION";
export const USER_MOMENT = "USER_MOMENT";
export const CHANGE_FLOOR = "CHANGE_FLOOR";
export const UPDATE_NODE_INFO = "UPDATE_NODE_INFO";
export const RESET_NODE_INFO = "RESET_NODE_INFO";
export const UPDATE_TRIP_DATA = "UPDATE_TRIP_DATA";
